[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.3.5", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15.7"
icalendar = "0.17.5"
serde_json = "1.0.145"
yew = { version = "0.22.0", features = ["csr"] }
